services:
  docker:
    build: ./docker
    container_name: docker_c
    ports:
      - "5000:8080"
    volumes:
      - ./docker:/app
      - /app/node_modules
  react:
    build: ./react
    container_name: ticTacToe_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
